spring.application.name=${APPLICATION_NAME:notification-service}
server.port=${SERVER_PORT:8080}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED:true}
spring.mail.properties.mail.smtp.connectiontimeout=${SMTP_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${SMTP_READ_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${SMTP_WRITE_TIMEOUT:5000}
notification.email.from=${SMTP_FROM:${spring.mail.username}}
